//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lista7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int EstudianteId { get; set; }
        public string EstudianteNombre { get; set; }
        public string EstudianteGenero { get; set; }
    }
}
